@echo off
REM Windows Users: Run this .bat file from the project root.

ECHO Installing root Node modules...
call npm install

ECHO Moving to \api...
ECHO Installing back-end Node modules...
cd "%cd%\api"
call npm install

ECHO Moving to \client...
ECHO Installing front-end Node modules...
cd "%cd%\..\client"
call npm install